apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sboms
  annotations:
    {{ .Values.storage.reclaimPolicyAnnotation }}: {{ .Values.storage.reclaimPolicy }}
{{ include "sbomer.labels" (list . "service") | indent 2 }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.service.storage.size }}
