{{ if .Values.service.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-secure
  annotations:
    haproxy.router.openshift.io/timeout: 10m
    haproxy.router.openshift.io/disable_cookies: "true"
    haproxy.router.openshift.io/balance: roundrobin
{{ include "sbomer.labels" (list . "service") | indent 2 }}
spec:
  host: {{ .Values.service.route.host }}
  to:
    kind: Service
    name: {{ include "sbomer.routeTarget" . }}
    weight: 100
  wildcardPolicy: None
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{- if .Values.service.route.tls.enabled }}
    key: |-
{{ .Values.service.route.tls.key | indent 6 }}
    certificate: |-
{{ .Values.service.route.tls.certificate | indent 6 }}
    caCertificate: |-
{{ .Values.service.route.tls.caCertificate | indent 6 }}
{{- end }}
{{ end }}
