{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sbomer.serviceAccountName" . }}
{{ include "sbomer.labels" (list .) | indent 2 }}
imagePullSecrets:
  - name: sbomer-redhatio-pull-secret
  - name: sbomer-quayio-pull-secret
---
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
{{ include "sbomer.labels" (list .) | indent 2 }}
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
{{ include "sbomer.labels" (list .) | indent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sbomer.serviceAccountName" . }}
