= Environment Setup
:tekton-version: v0.59.6

This page provides a list of actions that needs to be performed and tools that needs to be installed
in order to develop SBOMer.

Everything on this page is mostly a one-off preparation and will not
be repeated unless you will decide to start from scratch.

== Tools

Please install required tools.

=== JDK 17

SBOMer is developed using JDK 17.

You can use link:https://sdkman.io/[SDKMAN!] to install and manage JDKs.

==== Automatic Setup

To install java 17.0.12-tem using SDKMAN! run the `./hack/sdkman-setup.sh` command.

The script automatically sets `sdkman_auto_env=true` in [filename]`$HOME/.sdkman/etc/config` so that SDKMAN! will switch
to the correct JDK upon entering the project root directory due to the presence of the [filename]`.sdkmanrc` file in
that directory.

==== Manual Setup

To install java 17.0.12-tem manually using SDKMAN! follow these steps.

[source,console]
----
sdk install java 17.0.12-tem
----

[TIP]
====
Run `sdk list java` to get a list of all available Java versions!
====

When you enter the project directory you can run:

[source,console]
----
sdk env
----

And you're all set!

[TIP]
====
You can add to [filename]`$HOME/.sdkman/etc/config` file following entry:

[source,bash]
----
sdkman_auto_env=true
----

And SDKMAN! will switch to the correct JDK when entering the project directory.
See [filename]`.sdkmanrc` file in the project root directory.
====

=== Node.js

To be able to build our UI you need to install Node.js. The easiest option is to use
link:https://github.com/nvm-sh/nvm[Node Version Manager (nvm)].

Install it according to the instructions for your operating system. Once available
you can use it to install the `lts/jod` release, like this:


[source,console]
----
nvm install lts/jod
---

When you launch a new console you may need to select the Node.js version to use:

[source,console]
----
nvm use lts/jod
---

=== Minikube

Minikube will provide our local Kubernetes cluster where SBOMer will be performing the work.

Please follow link:https://minikube.sigs.k8s.io/docs/start/[upstream documentation] on how to install Minikube.

=== Helm

Helm is used by us to manage SBOMer deployments.

We have created comprehensive xref:helm.adoc[Helm guide]. Please follow it to get more information about Helm installation and usage.

== Configuration

This section focuses on setting up the tools.

[#minikube-setup]
=== Minikube Setup

To prepare minikube just run the `./hack/minikube-setup.sh` command.

[source,console]
----
$ ./hack/minikube-setup.sh
😄  [sbomer] minikube v1.35.0 on Fedora 42
✨  Using the kvm2 driver based on user configuration
💾  Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2-...:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2-...:  14.14 MiB / 14.14 MiB  100.00% 13.07 MiB
💿  Downloading VM boot image ...
    > minikube-v1.35.0-amd64.iso....:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > minikube-v1.35.0-amd64.iso:  345.38 MiB / 345.38 MiB  100.00% 11.62 MiB p
👍  Starting "sbomer" primary control-plane node in "sbomer" cluster
💾  Downloading Kubernetes v1.29.14 preload ...
    > preloaded-images-k8s-v18-v1...:  352.64 MiB / 352.64 MiB  100.00% 11.69 M
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm:  46.46 MiB / 46.46 MiB [------------] 100.00% 12.59 MiB p/s 3.9s

🐳  Preparing Kubernetes v1.29.14 on Docker 27.4.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "sbomer" cluster and "default" namespace by default
----

[NOTE]
====
This script uses the `kvm2` link:https://minikube.sigs.k8s.io/docs/drivers/[minikube driver]. If you don't use KVM,
you may want to adjust this command.
====

=== Firewall Adjustments

We will be mounting directories from the minikube instance into the host. If you have `firewalld` installed, then most likely the firewall will
prevent us from doing it. But we really, really need to do it. Let's allow it:

[source,console]
----
sudo firewall-cmd --permanent --zone=libvirt --add-rich-rule='rule family="ipv4" source address="192.168.39.0/24" accept'
sudo firewall-cmd --reload
----

[#managing-kubernetes-contexts]
=== Managing Kubernetes Contexts

It's very easy to run commands against wrong Kubernetes cluster. To minimize the risk of damage we
suggest using named contexts.

You can always check what is the current context:

[source,console]
----
kubectl config current-context
$ sbomer
----

[TIP]
====
You can list all available contexts with the `kubectl config get-contexts` command.
====

We suggest to rename the `sbomer` context into `sbomer-local`, like this:

[source,console]
----
$ kubectl config rename-context sbomer sbomer-local
Context "sbomer" renamed to "sbomer-local".
----

We will use the `sbomer-local` context when issues some commands later, but for now, let's
make sure we use it:

[source,console]
----
$ kubectl config use-context sbomer-local
Switched to context "sbomer-local".
----

=== Tekton Installation

We need to install Tekton manually. To be as close as possible to the staging and production deployment we should use
similar version of Tekton for development as deployed on the target environments. Currently it is `{tekton-version}`.

[source,console,subs="attributes+"]
----
$ kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/{tekton-version}/release.yaml
namespace/tekton-pipelines created
clusterrole.rbac.authorization.k8s.io/tekton-pipelines-controller-cluster-access created
clusterrole.rbac.authorization.k8s.io/tekton-pipelines-controller-tenant-access created
clusterrole.rbac.authorization.k8s.io/tekton-pipelines-webhook-cluster-access created
clusterrole.rbac.authorization.k8s.io/tekton-events-controller-cluster-access created
role.rbac.authorization.k8s.io/tekton-pipelines-controller created
role.rbac.authorization.k8s.io/tekton-pipelines-webhook created
role.rbac.authorization.k8s.io/tekton-pipelines-events-controller created
role.rbac.authorization.k8s.io/tekton-pipelines-leader-election created
role.rbac.authorization.k8s.io/tekton-pipelines-info created
serviceaccount/tekton-pipelines-controller created

...

deployment.apps/tekton-pipelines-remote-resolvers created
service/tekton-pipelines-remote-resolvers created
horizontalpodautoscaler.autoscaling/tekton-pipelines-webhook created
deployment.apps/tekton-pipelines-webhook created
service/tekton-pipelines-webhook created
----

== You Are Set!

Now you can proceed to the xref:development-guide.adoc[development guide page].

=== What If My Environment Is Not Working?

You can always start from scratch! To remove the minikube environment just run this command and
follow the guide again.

[source,console]
----
$ ./hack/minikube-delete.sh
🔥  Deleting "sbomer" in kvm2 ...
💀  Removed all traces of the "sbomer" cluster.
----
