name: Checkout source code
description: "Checks out source hopefully in a secure way"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  triggering-actor:
    required: true
    description: "The GitHub triggering actor"
  repo-ref:
    required: true
    description: "Repository full name"
  repo-full-name:
    required: true
    description: "Repository ref to check out"

runs:
  using: "composite"
  steps:
    - name: Get User Permission
      id: checkAccess
      uses: actions-cool/check-user-permission@v2
      with:
        require: write
        username: ${{ inputs.triggering-actor }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Check User Permission
      if: steps.checkAccess.outputs.require-result == 'false'
      shell: bash
      run: |
        echo "${{ inputs.triggering-actor }} does not have permissions on this repo."
        echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
        exit 1

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.repo-ref }}
        repository: ${{ inputs.repo-full-name }}
