# https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b
FROM registry.access.redhat.com/ubi9@sha256:1fafb0905264413501df60d90a92ca32df8a2011cbfb4876ddff5ceb20c8f165

RUN INSTALL_PKGS="jq wget unzip zip git" && \
    dnf --disableplugin=subscription-manager -y --nodocs --setopt=install_weak_deps=0 install $INSTALL_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/* /var/log/dnf* /var/log/yum.*

RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
RUN chmod a+x /usr/local/bin/yq

WORKDIR /workdir

ENV HOME=/workdir \
    SBOMER_DOMINO_DIR="/workdir" \
    SBOMER_MAVEN_SETTINGS_XML_PATH="/workdir/settings.xml" \
    SBOMER_GRADLE_SETTINGS_XML_PATH="/workdir/cyclonedx-init.gradle"

COPY certs/2022-IT-Root-CA.pem /etc/pki/ca-trust/source/anchors/2022-IT-Root-CA.pem
COPY certs/2015-IT-Root-CA.pem /etc/pki/ca-trust/source/anchors/2015-IT-Root-CA.pem

RUN update-ca-trust

RUN chown -R 65532:0 /workdir && \
    chmod -R g=u /workdir

USER 65532

COPY --chown=65532:0 \
    images/sbomer-generator/settings.xml \
    images/sbomer-generator/cyclonedx-init.gradle \
    images/sbomer-generator/install.sh \
    images/sbomer-generator/sdk_nvm_find_closest_installed_software.sh \
    /workdir/

RUN sh -c ./install.sh

COPY --chown=65532:0 cli/target/quarkus-app/lib/ /workdir/generator/lib/
COPY --chown=65532:0 cli/target/quarkus-app/*.jar /workdir/generator/
COPY --chown=65532:0 cli/target/quarkus-app/app/ /workdir/generator/app/
COPY --chown=65532:0 cli/target/quarkus-app/quarkus/ /workdir/generator/quarkus/
