# https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b
FROM registry.access.redhat.com/ubi9@sha256:fc300be6adbdf2ca812ad01efd0dee2a3e3f5d33958ad6cd99159e25e9ee1398

RUN INSTALL_PKGS="jq unzip zip git" && \
    dnf --disableplugin=subscription-manager -y --nodocs --setopt=install_weak_deps=0 install $INSTALL_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/* /var/log/dnf* /var/log/yum.*

WORKDIR /workdir
ENV HOME=/workdir

RUN chown -R 65532:0 /workdir && \
    chmod -R g=u /workdir

COPY --chown=65532:0 images/sbomer-generator/install_cert.sh /workdir/
RUN sh -c ./install_cert.sh

USER 65532

COPY --chown=65532:0 \
    images/sbomer-generator/settings.xml \
    images/sbomer-generator/cyclonedx-init.gradle \
    images/sbomer-generator/install.sh \
    images/sbomer-generator/install_nvm.sh \
    images/sbomer-generator/sdk_nvm_find_closest_installed_software.sh \
    /workdir/

RUN touch /workdir/.npmrc && \
    chmod 644 /workdir/.npmrc

RUN sh -c ./install.sh
RUN sh -c ./install_nvm.sh

ENV SBOMER_DOMINO_DIR="/workdir"
ENV SBOMER_MAVEN_SETTINGS_XML_PATH="/workdir/settings.xml"
ENV SBOMER_GRADLE_SETTINGS_XML_PATH="/workdir/cyclonedx-init.gradle"

COPY --chown=65532:0 cli/target/quarkus-app/lib/ /workdir/generator/lib/
COPY --chown=65532:0 cli/target/quarkus-app/*.jar /workdir/generator/
COPY --chown=65532:0 cli/target/quarkus-app/app/ /workdir/generator/app/
COPY --chown=65532:0 cli/target/quarkus-app/quarkus/ /workdir/generator/quarkus/
