# https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b
# Based on tag 9.2-755.1696515532
FROM registry.access.redhat.com/ubi9@sha256:2f168398c538b287fd705519b83cd5b604dc277ef3d9f479c28a2adb4d830a49

RUN INSTALL_PKGS="jq unzip zip git" && \
    dnf --disableplugin=subscription-manager -y --nodocs --setopt=install_weak_deps=0 install $INSTALL_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/* /var/log/dnf* /var/log/yum.*

WORKDIR /workdir
ENV HOME=/workdir

RUN chown -R 65532:0 /workdir && \
    chmod -R g=u /workdir

COPY --chown=65532:0 images/sbomer-generator/install_cert.sh /workdir/
RUN sh -c ./install_cert.sh

USER 65532

COPY --chown=65532:0 \
    images/sbomer-generator/settings.xml \
    images/sbomer-generator/cyclonedx-init.gradle \
    images/sbomer-generator/install.sh \
    images/sbomer-generator/sdk_find_closest_installed_software.sh \
    /workdir/
RUN sh -c ./install.sh

ENV SBOMER_DOMINO_DIR="/workdir"
ENV SBOMER_MAVEN_SETTINGS_XML_PATH="/workdir/settings.xml"
ENV SBOMER_GRADLE_SETTINGS_XML_PATH="/workdir/cyclonedx-init.gradle"

COPY --chown=65532:0 cli/target/quarkus-app/lib/ /workdir/generator/lib/
COPY --chown=65532:0 cli/target/quarkus-app/*.jar /workdir/generator/
COPY --chown=65532:0 cli/target/quarkus-app/app/ /workdir/generator/app/
COPY --chown=65532:0 cli/target/quarkus-app/quarkus/ /workdir/generator/quarkus/
