= Configuration

Although SBOMer was designed in a way it should not require user interaction to generate SBOMs,
there is a requirement to ensure the relationship between the generated SBOM and a particular product
release is maintained.

After suggestion from PST a decision has been made to use the Errata Tool identifiers of the product to
identify the product release for a particular SBOM. This data needs to be provided to SBOMer in some way.

There are currently three options:

1. Update the internal link:https://github.com/project-ncl/sbomer/blob/main/cli/src/main/resources/mapping/prod/product-mapping.yaml[SBOMer mapping file],
2. Provide required data in a configuration file,
3. Provide required configuration as part of the REST API invocation.

SBOMer configuration file, besides providing the product mapping, can adjust the generation process as well.
In most cases defaults will be a good fit, but sometimes changes will be required.

In any case, the resulting configuration (user provided + defaults) is validated against schema to ensure
a valid configuration.

NOTE: If you are unsure about what settings should be used, don't hesitate to contact SBOMer developers!

Below you can see an example configuration file.

[source,yaml]
----
# Optional, can be omitted. If not provided -- latest version will be assumed.
apiVersion: sbomer.jboss.org/v1alpha1
# Array of products
products:
  - processors:
      # Custom processors configuration (optional)
      # Please note that this is an array!

      # Specific processor configuration
      # All processors and available configs are listed below
      - processors:
          - type: redhat-product
            errata:
              productName: "RHTESTPRODUCT"
              productVersion: "RHEL-8-RHTESTPRODUCT-1.1"
              productVariant: "8Base-RHTESTPRODUCT-1.1"

    generator:
      # Custom generator configuration (optional)

      type: maven-cyclonedx

      # Additional arguments passed to the generator.
      args: "--batch-mode"

      # Version of the generator.
      version: 2.7.9
----

Please note that the `products` element is an array! This makes it possible to cover the unusual
case where a single build results in multiple product releases.

This file should be stored in the Gerrit repository that is used by the PNC Build Configuration under
the `.sbomer/config.yaml` path.

== Examples

Example of support for multi-product source code repository where a single build (configuration)
in PNC can build more than one product. In the example below have two products defined.

[source,yaml]
----
apiVersion: sbomer.jboss.org/v1alpha1
products:
  - processors:
      - type: redhat-product
        errata:
          productName: "CCCDDD"
          productVersion: "CCDD"
          productVariant: "CD"
    generator:
      type: maven-domino
      args: "--config-file .domino/cccddd.json --warn-on-missing-scm"
      version: "0.0.104"

  - processors:
      - type: redhat-product
        errata:
          productName: "AAABBB"
          productVersion: "AABB"
          productVariant: "AB"
    generator:
      type: maven-domino
      customArgs: "--config-file .domino/aaabbb.json --warn-on-missing-scm"
----

A single product (most common use case) where only the required configuration for the
`redhat-product` processor is provided. For everything else default values are used.

[source,yaml]
----
apiVersion: sbomer.jboss.org/v1alpha1
products:
  - processors:
      - type: redhat-product
        errata:
          productName: "RHBQ"
          productVersion: "RHEL-8-RHBQ-2.13"
          productVariant: "8Base-RHBQ-2.13"
----

== Generator configuration

There are three types of configuration options passed to the generator tool:

1. *Static* -- Options that are set always,
2. *Defaults* -- Parameters that are set additionally to the static options in case no custom options are provided.
3. *Custom* -- Parameters that are set in the configuration file. These are added to the static options. These options override defaults mentioned above.

Currently *default generator* is the CycloneDX Maven Plugin generator.

=== Domino Maven generator

* Type: `maven-domino`
* Default version: `0.0.104`.

Below you can see the static and default parameters set for the Domino generator.

**Static**

[source,console]
----
$ java -jar domino.jar report --project-dir=[DIR] --output-file=[OUTPUT_DIR]/bom.json --manifest -s [PATH_TO_SETTINGS_XML_FILE]
----

**Defaults**

[source,console]
----
--include-non-managed --warn-on-missing-scm
----

**Custom arguments**

Run the `java -jar domino.jar report --help` command to get a list of all possible options for Domino.

=== CycloneDX Maven Plugin generator

* Type: `maven-cyclonedx`
* Default version: `2.7.9`.

Below you can see the static and default parameters set for the CycloneDX Maven Plugin generator.

*Static*

[source,console]
----
$ mvn org.cyclonedx:cyclonedx-maven-plugin:[VERSION]:makeAggregateBom -DoutputFormat=json -DoutputName=bom --settings [PATH_TO_SETTINGS_XML_FILE]
----

*Defaults*

[source,console]
----
--batch-mode
----

*Custom arguments*

See the link:https://github.com/CycloneDX/cyclonedx-maven-plugin[plugin readme] for more
information on what other options can be passed to the tool.

== Processors

Below you can find a list of supported processors and the configuration options for each one.

Please note that this configuration does not influence *which processors are run*. The SBOMer
service configuration controls this if. If there are missing processors, these will be added.

Currently following processors are required to run (in order):

1. `default`
2. `redhat-product`

=== `default`

This processor adds available information from the PNC build system into the SBOM.

There are no configuration options for this processor.

=== `redhat-product`

This processor adds Red Hat product information metadata into the main component of the SBOM.

Configuration:

[source,yaml]
----
type: redhat-product:
errata:
  productName: [ET_PRODUCT_NAME] # required
  productVersion: [ET_PRODUCT_VERSION] # required
  productVariant: [ET_PRODUCT_VARIANT] # required
----
