= Examples

This page provides examples of common use cases of the SBOMer API.

== Manifests

=== Fetching all manifests

Please note that the return is a list of SBOMs in a paginated way.

[source,console,subs="attributes+"]
----
$ curl {sbomer-url}/api/{sbomer-latest-api-version}/manifests
----

=== Requesting manifest generation

To request manifest generation we need to use the `/api/{sbomer-latest-api-version}/generations` and provide
a xref:generation/configuration/index.adoc[generation request configuration] as the body.

Below you can see examples grouped by the type of the deliverable to manifest.

NOTE: The `/api/{sbomer-latest-api-version}/generations` accepts JSON (`application/json`) as well as YAML (`application/yaml`) content.

==== Container image

TIP: See xref:generation/configuration/image.adoc[image configuration].

Request manifest generation for the `registry.redhat.io/jboss-webserver-5/jws58-openjdk17-openshift-rhel8@sha256:3e28c6353bb1fdfe2a70dec5d840f2ef03a47bf2c9c92507982dca566fac0898` container image.

[source,console,subs="attributes+"]
----
$ curl -v -X POST {sbomer-url}/api/{sbomer-latest-api-version}/generations \ 
  -H 'accept: application/json' -H 'Content-Type: application/json' \
  -d '{
  "type": "image",
  "image": "registry.redhat.io/jboss-webserver-5/jws58-openjdk17-openshift-rhel8@sha256:3e28c6353bb1fdfe2a70dec5d840f2ef03a47bf2c9c92507982dca566fac0898"
}'
----

==== PNC build

TIP: See xref:generation/configuration/pnc-build.adoc[PNC build configuration].

Request manifest generation for the `A7IGVJ7N2DYAA` PNC build.

[source,console,subs="attributes+"]
----
$ curl -v -X POST {sbomer-url}/api/{sbomer-latest-api-version}/generations \ 
  -H 'accept: application/json' -H 'Content-Type: application/json' \
  -d '{
  "type": "pnc-build",
  "buildId": "A7IGVJ7N2DYAA"
}'
----

==== PNC Analysis

TIP: See xref:generation/configuration/pnc-analysis.adoc[PNC analysis configuration].

Request manifest generation for following zips, storing the results under PNC milestone ID 1234:

- https://download.host.com/staging/product-a/release-b/first.zip
- https://download.host.com/staging/product-a/release-b/second.zip

Please note that you must provide a valid PNC milestone ID or analysis will fail.

[source,console,subs="attributes+"]
----
$ curl -v -X POST {sbomer-url}/api/{sbomer-latest-api-version}/generations \ 
  -H 'accept: application/json' -H 'Content-Type: application/json' \
  -d '{
  "type": "pnc-analysis",
  "milestoneId": "1234",
  "urls": [
    "https://download.host.com/staging/product-a/release-b/first.zip",
    "https://download.host.com/staging/product-a/release-b/second.zip"
  ]
}'
----

==== Errata Advisory

TIP: See xref:generation/configuration/errata-advisory.adoc[Errata Advisory configuration].

Request manifest generation for content attached to advisory `1234`:

[source,console,subs="attributes+"]
----
$ curl -v -X POST {sbomer-url}/api/{sbomer-latest-api-version}/generations \ 
  -H 'accept: application/json' -H 'Content-Type: application/json' \
  -d '{
  "type": "errata-advisory",
  "advisoryId": 1234
}'
----

==== PNC Deliverable Analyser operation

TIP: See xref:generation/configuration/pnc-operation.adoc[PNC operation configuration].

Request manifest generation for the `BBNOWAGR3EYAA` PNC Deliverables Analyser operation:

[source,console,subs="attributes+"]
----
$ curl -v -X POST {sbomer-url}/api/{sbomer-latest-api-version}/generations \ 
  -H 'accept: application/json' -H 'Content-Type: application/json' \
  -d '{
  "type": "pnc-operation",
  "operationId": "BBNOWAGR3EYAA"
}'
----

=== Fetching a specific manifest

After the manifest is generated it will become available at:

[source,console,subs="attributes+"]
----
$ curl {sbomer-url}/api/{sbomer-latest-api-version}/manifests/[MANIFEST_ID]
----

TIP: As the identifier you can use the manifest ID or the main component's link:https://github.com/package-url/purl-spec[purl].


== Generations

Generations provide information on the progress of the generation.

=== Fetching all generations

Please note that the return is a list of generations in a paginated way.

[source,console,subs="attributes+"]
----
$ curl {sbomer-url}/api/{sbomer-latest-api-version}/generations
----

=== Fetching specific generation

Get a specific generation request:

[source,console,subs="attributes+"]
----
$ curl {sbomer-url}/api/{sbomer-latest-api-version}/generations/[REQUEST_ID]
----
