
# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
# Based on tag 1-95
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:0324317aa0780d1cc31a60d68be654493fe4582d208e60a7737c57e2575bfc25

USER root

COPY images/sbomer-cache/nginx.conf.template /etc/nginx/nginx.conf.template
RUN mkdir -p /var/www/cache
RUN chown 1001:0 /var/www/cache

USER default

CMD nginx -g "daemon off;"
