
# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
# Based on tag 1-95
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:b59b3324e004d7226f7134c921bcedaf335ef6355fe663e3b8f5e4f31b81a19d

USER root

COPY images/sbomer-cache/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /var/www/cache
RUN chown 1001:0 /var/www/cache

USER default

CMD nginx -g "daemon off;"