
# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
# Based on tag 1-116.1692771028
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:88448b7e65fff757d6558f20b2994d8ba89eb8aaa9099fc77746ec704ec58fe4

USER root

COPY images/sbomer-cache/nginx.conf.template /etc/nginx/nginx.conf.template
RUN mkdir -p /var/www/cache
RUN chown 1001:0 /var/www/cache

USER default

CMD nginx -g "daemon off;"
