FROM registry.access.redhat.com/ubi9@sha256:4ea5966341930537784fd14b19073fb2af58d11b302332bb5dc445e0851b286d

RUN INSTALL_PKGS="jq unzip zip git" && \
    dnf -y --nodocs --setopt=install_weak_deps=0 install $INSTALL_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/* /var/log/dnf* /var/log/yum.*

RUN curl -k -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt \
    https://password.corp.redhat.com/RH-IT-Root-CA.crt && \ 
    /usr/bin/update-ca-trust

WORKDIR /workdir
ENV HOME=/workdir

RUN chown -R 65532:0 /workdir && \
    chmod -R g=u /workdir

USER 65532

COPY --chown=65532:0 src/main/images/generator/settings.xml src/main/images/generator/install.sh /workdir/
RUN sh -c ./install.sh
