#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"15":
  products:
    - processors:
        - type: redhat-product
          errata:
            productName: RHTESTPRODUCT
            productVersion: RHEL-8-RHTESTPRODUCT-1.1
            productVariant: 8Base-RHTESTPRODUCT-1.1
      generator:
        type: maven-cyclonedx
"382":
  products:
    - processors:
        - type: redhat-product
          errata:
            productName: RHBQ
            productVersion: Middleware-RHBQ-2.13
            productVariant: 8Base-MW-RHBQ-2.13
      generator:
        type: maven-domino
        args: "--config-file .domino/manifest/quarkus-bom-config.json --warn-on-missing-scm --legacy-scm-locator"
    # TODO: Enable these when we know what are the Errata Tool coordinates
    # - generator:
    #     type: maven-domino
    #     args: "--config-file .domino/manifest/quarkus-camel-bom-config.json --warn-on-missing-scm"
    # - generator:
    #     type: maven-domino
    #     args: "--config-file .domino/manifest/quarkus-optaplanner-bom-bom.json --warn-on-missing-scm"
    # - generator:
    #     type: maven-domino
    #     args: "--config-file .domino/manifest/quarkus-qpid-jms-bom-bom.json --warn-on-missing-scm"
"484":
  products:
    - processors:
        - type: redhat-product
          errata:
            productName: RHBQ
            productVersion: Middleware-RHBQ-3.2
            productVariant: 8Base-MW-RHBQ-3.2
      generator:
        type: maven-domino
        args: "--config-file .domino/manifest/quarkus-bom-config.json --warn-on-missing-scm --legacy-scm-locator"
"436":
  products:
    - processors:
        - type: redhat-product
          errata:
            productName: Migration Toolkit for Runtimes
            productVersion: RHEL-8-MTR-1
            productVariant: 8Base-MTR-1
      generator:
        type: maven-cyclonedx
