name: On Label

on:
    pull_request:
        types:
            - labeled

jobs:
  build:
    if: github.event.label.name == 'ok-to-build'
    name: "Code"
    uses: ./.github/workflows/build-code.yml
    secrets: inherit

  build-ui:
    if: github.event.label.name == 'ok-to-build'
    name: "UI"
    uses: ./.github/workflows/build-ui.yml
    secrets: inherit






